spring.application.name: SpringSecurityJwtDemo
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username:
    password:
rsaPublicKey: >
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnpfFQwblHRfSgy40LyR/
  4AdiZiPVUcv4+AWyqz1YntajD2t8GHZo9laxqmCsGnpKC3Qw1qpllLHlc6r5vz7P
  sc9XzULWCHP1vck4uV4w8auIRZ1xpGD27YG5MNrm5uqNPkGMkMMf5aedB0ZwJ2nE
  jJYGL7vrepYcVtpL3TaQCK5fJ8TPWO/ctFQk5hBSd1reRbNb/vvZl5Y9ZQSRbdXM
  2VQ/0S6vRcvOmhZ5qQz1N6hJjez0ymIsAWE2aO3UClVdCcom4KHUiHi/PM0iK69f
  mG6IgzPIbbJ3O06OIVLC7nz/NjuMUVz2wVQnFo/bR5KTb2IGpRqBuS2Nft+vwpKN
  ZQIDAQAB
rsaPrivateKey: >
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCel8VDBuUdF9KD
  LjQvJH/gB2JmI9VRy/j4BbKrPVie1qMPa3wYdmj2VrGqYKwaekoLdDDWqmWUseVz
  qvm/Ps+xz1fNQtYIc/W9yTi5XjDxq4hFnXGkYPbtgbkw2ubm6o0+QYyQwx/lp50H
  RnAnacSMlgYvu+t6lhxW2kvdNpAIrl8nxM9Y79y0VCTmEFJ3Wt5Fs1v++9mXlj1l
  BJFt1czZVD/RLq9Fy86aFnmpDPU3qEmN7PTKYiwBYTZo7dQKVV0JyibgodSIeL88
  zSIrr1+YboiDM8htsnc7To4hUsLufP82O4xRXPbBVCcWj9tHkpNvYgalGoG5LY1+
  36/Cko1lAgMBAAECggEAFg7Xc7NjjgiYccDtJqpts7/rLngo7SPQ2NRYDauuZgdF
  7jjdrXxYrHyR4PfpsBQWtOGgAld4YfZdStl6u6AVnK5RUL4NTWcthIxWfKfOaGqa
  fU5A9mM7LP0YQCSOLYttgj11OtQ83UETHOYt5rl2CjS6nwyE28vBnM3nc9jpLx+z
  e6QM7IiIqXvYAe7od8RRNDy66HgyIfG/2qsaWQhq0c8YyVU4a5nv004xdkkDeMst
  aWJ+14a4gBzShWrNkYxbozjUOGGZwNE8QCubvSxBmqpYop/JprImH+vWeHmOE53T
  6Aj503HKuvvyOVZYVlEfT4y9vcEdBaqwpcHNH/JZAQKBgQDV1JYbgbIMSeI7sXV5
  bxvOq2tZU14hNeeCKPka6bE9yOrmxE07f62X6CQpYw62pJbJYNCRou8s2SVPs2nr
  cjBqmvSjxczJBHNEJthqSEc8+El16gZ3hhEXqCh/09OYDoLKAzDjwM3UDBCFwv0K
  F7u8vK9gpNUpxDhEvlwo/ZSlAQKBgQC93nfTlM7cEEAd6bKzmrNYzd4uzM81to0V
  nR8Ao/SYGd8VbJC+Uq+8s7OJWW9/BwpVUvb8bSIDcBDbhH28whO2Nbl6ZIK9GvFD
  zbDP0py5KY0VUsqpEgtFqiMaXQbkkua8xMGD9yR/67kBOJiaz2Wq2IbQXfra2/pP
  P4PC7yl0ZQKBgQCfSKvEs7kg5EytMMUUf0rUieb+dFazIIdi8wiVHq3UG324B1SM
  1NBITznYxpxoO3TDb+YOBrRp0Ru1Ii3toHMmhmVkNe0VdMY0Z0dg7JR8e2uldX35
  vRmwaKg6iF2fcHfG6deaYL4yjgYkzhpWUVWdA2UU9dSAN1W/B5p5QmRfAQKBgHwZ
  MzKseYQmbvHeNHnlrEFn1Ue7f9e4qIAvAPt3LkBX8JJdMkHjY4+v2LH2LcTWAjAA
  mQQmBGxAzBPehhxgsWePt9pCZZ1aRcUuZNmA7ASuHtOIGIPnEk0HRghOM1oklgFd
  jKpHV6jwliwxJLVSxz2iZoM8WeDAlNtFRUac8PhtAoGBAI46GlcdswBnTqOEzoOq
  QRHR+j0+NOYq9BN9vKKFxFTOTIgvQWGzLib5G3DdijjQi6r/+ildBn8Cv9WCTCgZ
  mrbd8AOOBjT1/Bt/APidva62BPDsunaBo7RUbpVQKs8ZCg9ojso3QWfeYPlCzH8i
  qpJqnNA9qxSMfVJwJ7XGgh5M